version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    groups:
      python-deps:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      container-images:
        patterns: ["*"]
  - package-ecosystem: terraform
    directories:
      - /infra
      - /infra/terraform_state
    schedule:
      interval: weekly
    groups:
      terraform-providers:
        patterns: ["*"]
